### ISSUE TITLE
Training result problems

### ISSUE THREAD

**Issue by yijingshihenxiule** [lmnt-com/wavegrad#11]

**Comment by yijingshihenxiule** [comment]
Hi! 
I used your pretrained model and get quite good audio quality. But when I use LJ dataset to train myself about 30K steps, the result of inference is of no sound.   Could you help me solve this? I followed your steps in README.md.

**Comment by d-caviedes** [comment]
Ok, so basically there is a normalization due to expected 16bit mono wav files (amp ranging -32767.5, +32767.5). However, my LibriTTS were 32 bit and ranging (-1, 1), which obviously makes them not suitable for the normalization. It is possible that was your issue @yijingshihenxiule. I have very good results after 1Million iterations.

My suggestion for the code here is that the normalization is not hard coded as it is right now in 3 different files in the repo. But other than that, it is a flawless implementation.
